language: php
addons:
  chrome: stable
env:
  - TRAVIS_CHROME=google-chrome-stable 
php:
  - 7.0
  - 7.1
  - 7.2

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script: 
  - vendor/bin/phpunit ./tests
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml ./tests